word_level_gpt2model:
    config: 'https://drive.google.com/uc?id=162B5HtHfv2YF2WV2VHyO0-zs75Oczr3n&export=download'
    weight: 'https://drive.google.com/uc?id=1-3ck0xORtfWalOIDgjzr4Aj0jIuGTQR2&export=download'
    tokenizer:
        merges_file: 'https://drive.google.com/uc?id=1-4uDbTwBabYl05hTPZN97l6g7YK760rW&export=download'
        vocabs_file: 'https://drive.google.com/uc?id=1-73sKmR5dLE1uGUrXWkJTRa3hUUhwB_m&export=download'

syllable_level_gpt2model:
    config: 'https://drive.google.com/uc?id=1x1mTQ9u3LYp1Hi-fzo-yWkEhlLPcf_6S&export=download'
    weight: 'https://drive.google.com/uc?id=1-EuqPpyQbSJruXmjCbMgRVDeCyUKYe4x&export=download'
    tokenizer:
        merges_file: 'https://drive.google.com/uc?id=1-HZdP1xMRedtU9XCFwBeR6vCV6LToXUk&export=download'   
        vocabs_file: 'https://drive.google.com/uc?id=1-PcnPFqhACUs7uHOdG82qXzf6nbPrGIQ&export=download'

custom_loss_model:
    weight: 'https://drive.google.com/uc?id=1-QIGN7RIdBrzysijEGtx_bljQwh40hck&export=download'
    tokenizer:
        merges_file: 'https://drive.google.com/uc?id=1-S1aXkH7qmLOOj1koZR_fN6vGvRW5B_U&export=download'   
        vocabs_file: 'https://drive.google.com/uc?id=1-WDeSDHNwo2DbE-o5UOGLteWserp_9Jx&export=download'

bow:
    gia_dinh: 'https://drive.google.com/uc?id=1-ZJ9hvP9bJxfqXbeTYWBAimkAncTKnfA&export=download'
    tinh_yeu: 'https://drive.google.com/uc?id=1-abeedKBeHSSMCJUCcGVJkd4saVRqsIO&export=download'
    dich_benh: 'https://drive.google.com/uc?id=1-ccTIDCkDnZryoEbbjTSAVW3Fw3tYnS6&export=download'
    que_huong: 'https://drive.google.com/uc?id=1-e07NmmlxSPfphG7WC3DkcWY45gNw5t-&export=download'
    le_tet: 'https://drive.google.com/uc?id=1-e8rQSd9qHHTpu7NZoqIlTlkMLadAkhU&export=download'
